services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/backend/Dockerfile
    restart: always
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /backend
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    env_file:
      - .env
    secrets:
      - postgres_password

  db:
    image: postgres:17.2-alpine3.21
    restart: always
    shm_size: 128mb
    volumes:
      - db_volume:/data/postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    env_file:
      - .env
    secrets:
      - postgres_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.2-alpine

  nginx:
    build:
      context: ./backend
      dockerfile: docker/nginx/Dockerfile


volumes:
  db_volume:

secrets:
   postgres_password:
     file: db_password.txt