services:
  backend:
    build:
      context: ./backend/
      dockerfile: docker/backend/Dockerfile
    restart: on-failure
    develop:
      watch:
        - action: sync+restart
          path: ./backend/app
          target: /backend/app
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    env_file:
      - .env
    secrets:
      - postgres_password

  db:
    image: postgres:17.2-alpine3.21
    restart: always
    shm_size: 128mb
    volumes:
      - db_volume:/data/postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    env_file:
      - .env
    secrets:
      - postgres_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.2-alpine

  nginx:
    build:
      context: ./backend/nginx
      dockerfile: ../docker/nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    develop:
      watch:
        - action: sync+restart
          path: ./backend/nginx/nginx.conf
          target: /etc/nginx/nginx.conf
        - action: sync
          path: ./backend/nginx/data
          target: /usr/share/nginx/html


volumes:
  db_volume:

secrets:
   postgres_password:
     file: db_password.txt