services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: on-failure:3
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_PASSWORD_FILE: &postgres-password-file /run/secrets/postgres_password
    env_file: &env-file
      - .env
    secrets: &postgres-secret
      - postgres_password
    volumes:
      - "./backend:/backend"
      - data_storage_volume:/backend/data_storage

  db:
    image: postgres:17.2-alpine3.21
    restart: on-failure:3
    shm_size: 128mb
    volumes:
      - db_volume:/data/postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD_FILE: *postgres-password-file
    env_file: *env-file
    secrets: *postgres-secret

  redis:
    image: redis:7.4.2-alpine

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_volume:
  data_storage_volume:

secrets:
   postgres_password:
     file: db_password.txt