user nginx;
worker_processes auto;
worker_rlimit_nofile 42;

events {
    worker_connections  128;
    multi_accept        on;
    accept_mutex        off;
    use                 epoll;
}

http {
    server {
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
        }
        location /docs {
			proxy_pass http://backend:8080;
		}
    }

    server {
        server_name api.localhost;

        location / {
			proxy_pass http://backend:8080;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
		}
    }
}