"""rename photo_file field to photo_file_name in users table

Revision ID: ce8d48abcb2c
Revises: 96f80bece7f6
Create Date: 2025-02-12 15:02:08.553299

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8d48abcb2c'
down_revision: Union[str, None] = '96f80bece7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=42), nullable=False),
    sa.Column('hashed_password', sqlmodel.AutoString(), nullable=False),
    sa.Column('photo_file_name', sqlmodel.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
