"""do username field is unique in users table

Revision ID: d0a8746cd428
Revises: ce8d48abcb2c
Create Date: 2025-02-12 15:34:44.594888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a8746cd428'
down_revision: Union[str, None] = 'ce8d48abcb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_username", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_username", "users")
    # ### end Alembic commands ###
